# Generated by Django 5.1.8 on 2025-05-16 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 16, 12, 41, 29, 484591)),
            preserve_default=False,
        ),
    ]
