# Generated by Django 5.1.8 on 2025-05-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='question_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.session')),
            ],
        ),
    ]
