# Generated by Django 5.1.8 on 2025-05-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_session_name_session_question_count_sessionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
