# Generated by Django 5.1.8 on 2025-05-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_session_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='order',
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
