# Generated by Django 5.1.8 on 2025-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_session_end_time_session_start_time_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_per_question',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_time_limit',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
