# Generated by Django 5.1.8 on 2025-05-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_userprofile_time_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
