# Generated by Django 5.1.8 on 2025-05-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_session_duration_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
