# Generated by Django 5.1.8 on 2025-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='option_order',
            field=models.CharField(choices=[('O', 'По порядку'), ('R', 'Случайный')], default='O', max_length=1),
        ),
    ]
