# Generated by Django 5.1.8 on 2025-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_session_option_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text',
            field=models.CharField(default='', help_text='Здесь хранится ровно тот текст, который является правильным', max_length=255),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Длительность сессии в секундах'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('O', 'Порядок вопросов'), ('R', 'Случайно вопросы')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='option_order',
            field=models.CharField(choices=[('O', 'По порядку'), ('R', 'Случайно')], default='O', help_text='В каком порядке показывать варианты ответа', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
