# Generated by Django 5.1.8 on 2025-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
    ]
