# Generated by Django 5.1.8 on 2025-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_session_is_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('O', 'Порядок вопросов'), ('R', 'Случайно вопросы'), ('V', 'Variant')], default='O', max_length=1),
        ),
    ]
